### ISSUE TITLE
Feature request: auto swipe..

### ISSUE THREAD

**Issue by ceinmart** [zanna-37/hass-swipe-navigation#53] opened 2023-04-30 19:24 UTC
Hi , 

I don't know if is possible, a way to enable the to dashboard auto-swipe between pages. 
I have a tablet, it stays on the wall, and would be nice if each X second they auto-swipe to the next page. 

Probably should have a button on each page to turn on / off this auto swap..

**Comment by zanna-37** [comment] 2023-05-08 10:24
Unfortunately this is out of scope for this repo as its main purpose is to provide (touch) swipe navigation.

Duplicate of #44.

**Closed by zanna-37** 2023-05-08 10:24 UTC
Labels: 😶 wontfix
