### ISSUE TITLE
Feature request: set a timer to auto-return to default view

### ISSUE THREAD

**Issue by fredericuslaurentii** [zanna-37/hass-swipe-navigation#86] opened 2024-11-06 12:29 UTC
It might be useful to be able to set a timer so that after a swipe, the view automatically returns to a default view selected by the user.

This is especially useful if the main screen is always one.

**Comment by zanna-37** [comment] 2024-11-11 18:14
Duplicate of #44.

**Closed by zanna-37** 2024-11-11 18:14 UTC
Labels: 👥 duplicate
