### ISSUE TITLE
Define home tab index and enable auto return to home after specified time

### ISSUE THREAD

**Issue by kretherford0983** [zanna-37/hass-swipe-navigation#71] opened 2024-02-11 04:23 UTC
Would like to be able to define a home tab (default could be set to index 0) and then have the ability to define how many seconds after the last swipe that the dashboard will automatically return to the home tab. Would be nice when you have a tablet serving as an on wall dashboard control to always display a home tab after the last person used the dashboard and moved between tabs. This way you can always be sure the next time you use the dashboard your most desired cards/controls will be displayed.

**Comment by zanna-37** [comment] 2024-02-11 09:55
Duplicate of https://github.com/zanna-37/hass-swipe-navigation/issues/44.

**Closed by zanna-37** 2024-02-11 09:55 UTC
Labels: 👥 duplicate
