### ISSUE TITLE
Swipe will not let me access to a panel (1 card) view 

### ISSUE THREAD

**Issue by Luis84lp** [zanna-37/hass-swipe-navigation#80] opened 2024-09-13 10:23 UTC
Since last update I'm not able to swipe to reach a view configurated as a Panel (1 card) view, it will take me back to the first view.

**Comment by 5a2v0** [comment] 2024-09-13 13:14
Hi all.. me too! After last update i can swipe from first to third view and come back to the first. I can't go go the second view by swipe, only click the second view name at the top bar.

When i am on this second view, swipe does not work.

**Comment by imip** [comment] 2024-09-13 22:30
Same here since the last update 👍

**Comment by zanna-37** [comment] 2024-09-14 01:09
Can you share a minimal configuration that triggers the issue?

**Comment by CVKBaca** [comment] 2024-09-14 05:27
I have the same problem since the last update. I'm not using any custom configuration.

**Comment by Luis84lp** [comment] 2024-09-14 06:33
> Can you share a minimal configuration that triggers the issue?

Just create a new view and configure it as PANEL (1 CARD). You will not be able to reach to it with a swipe gesture. The content of the view is not relevant.

**Comment by ghizmo82** [comment] 2024-09-17 05:54
same problem since the last update

**Comment by zanna-37** [comment] 2024-09-18 20:39
Section doesn't work as well according to #81

**Comment by zanna-37** [comment] 2024-09-18 20:49
Crazy enough, I can't reproduce the bug, neither with Sections nor Panels. However, since many people reported it, I'm trying with a blind fix.
It's available on the new beta [`v1.14.2-beta1`](https://github.com/zanna-37/hass-swipe-navigation/releases/tag/v14.1.2-beta1).
Can you test it and report back? 🤞🏻
Thank you all.

**Comment by Luis84lp** [comment] 2024-09-18 20:55
Just tested it, unfortunately nothing has changed.
I don't have any problems with sections, just with panel view.
Thank you for your effort!

**Comment by zanna-37** [comment] 2024-09-18 21:03
Are you sure you [cleared the cache](https://github.com/zanna-37/hass-swipe-navigation/wiki/Clearing-your-Home-Assistant-cache)?

**Comment by Luis84lp** [comment] 2024-09-18 21:07
Yes I did, no changes. Sorry

**Comment by zanna-37** [comment] 2024-09-18 21:13
Are there any errors in console?
Any feedback from other people is also appreciated.

**Comment by Luis84lp** [comment] 2024-09-18 21:25
No errors in system - logs section.
In my case I have the panel view in the third position and if I swipe from
second view to third view it will jump directly to the first view.
If I swipe from fourth view to the third it will also jump directly to the
first view.

**Comment by zanna-37** [comment] 2024-09-18 21:47
By "logs in console" I mean the browser console. When using chrome, open the Chrome developer tools and search the console tab.

**Comment by Luis84lp** [comment] 2024-09-20 19:27
Sorry for the late reply.
There is no chrome console in Android devices. I could use the tracing
option (hidden developer mode in Chrome) to send you a trace file
(.pftrace.gz). Would that help?

**Comment by CVKBaca** [comment] 2024-09-21 12:15
Here is the translation:

After downgrading to version 1.13.3, swipe navigation between my dashboards is working again.

**Comment by 5a2v0** [comment] 2024-09-21 12:36
Hi CVKBaca, i tried it just now, after reading your post and it works to me also.

I tried also other 1.14.x avaiable versions and all of these give me the same problem

**Comment by ghizmo82** [comment] 2024-09-21 13:42
Same for me if I downgrade to version 1.13.3 and clear cache it comes back to work

**Comment by arn0ld2000** [comment] 2024-09-22 10:20
the input: path: "" in input view config on the cards is making those problems. 

![1](https://github.com/user-attachments/assets/5545231a-3d92-4134-8b55-2833e51aa37c)
![2](https://github.com/user-attachments/assets/6d0c6e91-baee-4620-80d6-68c0be10ece3)
![3](https://github.com/user-attachments/assets/805bdc95-5bae-4311-ac53-39216286ca32)

**Comment by Luis84lp** [comment] 2024-09-22 10:47
Correct, that fixes the problem! Great work!

**Comment by 5a2v0** [comment] 2024-09-22 10:58
> the input: path: "" in input view config upon all the views are making those problems.
> 
> Just simply remove the line: path: "" and it will start working to be swiped again.
> 
> ![1](https://private-user-images.githubusercontent.com/92170497/369680315-5545231a-3d92-4134-8b55-2833e51aa37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDI4NjksIm5iZiI6MTcyNzAwMjU2OSwicGF0aCI6Ii85MjE3MDQ5Ny8zNjk2ODAzMTUtNTU0NTIzMWEtM2Q5Mi00MTM0LThiNTUtMjgzM2U1MWFhMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDEwNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OGRlY2I1OTNhMTEyN2FkMWFjMzMyMjM2NTM4ODA5ZGQ0Nzc4MTE0OTFiMzVlYThhMGIyZWEwNGJhMjhiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IPdEBFBdEphb4rLAjvef6mENAvbvyx5Y-vboNLL4aMw) ![2](https://private-user-images.githubusercontent.com/92170497/369680320-6d0c6e91-baee-4620-80d6-68c0be10ece3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDI4NjksIm5iZiI6MTcyNzAwMjU2OSwicGF0aCI6Ii85MjE3MDQ5Ny8zNjk2ODAzMjAtNmQwYzZlOTEtYmFlZS00NjIwLTgwZDYtNjhjMGJlMTBlY2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDEwNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZjA0M2U2MGYzMzMzZGVjMGMzNjZmMzdkMjI5NzM2NmY2ZTk2MmY4NTU5ZTNiNTA1YjNmODMzNzQ5NGRiMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kv-DGNWOI9tmzK0yHcjoe6Ti_YBI_NUE40R1N15yjsY) ![3](https://private-user-images.githubusercontent.com/92170497/369680325-805bdc95-5bae-4311-ac53-39216286ca32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDI4NjksIm5iZiI6MTcyNzAwMjU2OSwicGF0aCI6Ii85MjE3MDQ5Ny8zNjk2ODAzMjUtODA1YmRjOTUtNWJhZS00MzExLWFjNTMtMzkyMTYyODZjYTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDEwNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNjI1YjU5NWU5NTY2NWRmNjQwOTI5Y2FiODY3NzgzZDY1YjhmMjlhY2FlYTRmNzUwMGIwN2JiYmVkOTA1YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W55XqqsNOt998oXpGB4pd_QAJWMo921cVzkbgalcb94)

remove or assign a path name will be fine.

I give a "path name" to each view and then downloaded again 1.14.1 and it works !

**Comment by zanna-37** [comment] 2024-09-22 13:58
Nice catch @arn0ld2000.
Thank you very much.
Everything should be fixed on the new pre-release `v1.14.2`.

**Closed by zanna-37** 2024-09-22 13:58 UTC
Labels: 🐛 bug
